fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            index_name: tugel
            settings:
                index:
                    analysis:
                        analyzer:
#                            default_index:
#                                type: whitespace
#                            default_search:
#                                type: whitespace
                            whitespace:
                                type: whitespace
                                lowercase: true
                            identifier:
                                type: pattern
                                pattern: "[\\:\\.\\W\\\\]+"
                                lowercase: false
                            camelcase:
                                type: pattern
                                pattern: "([^\\p{L}\\d]+)|(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)|(?<=[\\p{L}&&[^\\p{Lu}]])(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}[\\p{L}&&[^\\p{Lu}]])"
                                lowercase: true
            types:
                package:
                    indexable_callback: isIndexed
                    mappings:
                        id:
                          type: "integer"
                          store: "yes"
                        platform.id:
                          type: "integer"
                          store: "yes"
                        name:
                          type: "string"
                          store: "yes"
                        version:
                          type: "string"
                          store: "yes"
                        description:
                          type: "string"
                          store: "yes"
                        codeTagsMaximum:
                          type: "integer"
                          store: "yes"
                        codeTagsText:
                          type: "string"
                          store: "no"
                          analyzer: "camelcase"
#                        codeTags:
#                          type: "object"
#                          store: "yes"
#                          properties:
#                            name:
#                              type: "string"
#                            count:
#                              type: "float"
                        license:
                          type: "string"
                          store: "yes"
                        languages:
                          type: "string"
                          store: "no"
                          analyzer: "whitespace"
                        namespaces:
                          type: "string"
                          store: "no"
                          analyzer: "identifier"
                        classes:
                          type: "string"
                          store: "no"
                          analyzer: "identifier"
                    persistence:
                        driver: orm
                        model: Tugel\TugelBundle\Entity\Package
                        provider: ~
                        listener: ~
                        finder: ~