fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            index_name: tugel
            settings:
                index:
                    analysis:
                        analyzer:
#                            default_index:
#                                type: whitespace
#                            default_search:
#                                type: whitespace
                            whitespace:
                                type: whitespace
                                lowercase: true
                            identifier:
                                type: pattern
                                pattern: "[\\:\\.\\W\\\\]+"
                                lowercase: false
                            camelcase:
                                type: pattern
                                pattern: "([^\\p{L}\\d]+)|(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)|(?<=[\\p{L}&&[^\\p{Lu}]])(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}[\\p{L}&&[^\\p{Lu}]])"
                                lowercase: true
            types:
                package:
                    indexable_callback: isIndexed
                    mappings:
                        id:
                          type: "integer"
                        platform.id:
                          type: "integer"
                        name:
                          type: "string"
                        version:
                          type: "string"
                        description:
                          type: "string"
                        codeTagsMaximum:
                          type: "integer"
                        codeTagsText:
                          type: "string"
                          analyzer: "camelcase"
                          store: "no"
                        codeTags:
                          type: "object"
                          store: "yes"
                          properties:
                            name:
                              type: "string"
                            count:
                              type: "float"
                        languages:
                          type: "string"
                          analyzer: "whitespace"
                        namespaces:
                          type: "string"
                          analyzer: "identifier"
                        classes:
                          type: "string"
                          boost: 1
                          analyzer: "identifier"
                    persistence:
                        driver: orm
                        model: Tugel\TugelBundle\Entity\Package
                        provider: ~
                        listener: ~
                        finder: ~