fos_user:
    db_driver: orm
    user_class: FourTeachers\LehrerappBundle\Entity\User
    firewall_name: main
    registration:
        form:
            type: user_registration
        confirmation:
            enabled: true
            from_email:
                address:        lehrerapp@bzeutzheim.de
                sender_name:    Lehrerapp Konto
    resetting:
        email:
            from_email:
                address:        lehrerapp@bzeutzheim.de
                sender_name:    Lehrerapp Konto
    from_email:
        address:        lehrerapp@bzeutzheim.de
        sender_name:    Lehrerapp Konto
