fos_elastica:
  clients:
    default:
      host: localhost
      port: 9200
  indexes:
      default:
        index_name: tugel
        settings:
          index:
              number_of_replicas: 0
              number_of_shards: 1
              analysis:
                filter:
                  english_stop:
                    type: stop
                    stopwords: _english_
                  light_english_stemmer:
                    type: stemmer
                    language: light_english
                  english_possessive_stemmer:
                    type: stemmer
                    language: possessive_english
                tokenizer:
                  camelcase:
                    type: pattern
                    pattern: "([^\\p{L}\\d]+)|(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)|(?<=[\\p{L}&&[^\\p{Lu}]])(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}[\\p{L}&&[^\\p{Lu}]])"
                  version:
                    type: path_hierarchy
                    delimiter: "."
                char_filter:
                  version:
                    type: mapping
                    mappings:
                      - "-=>."
                      - "_=>."
                analyzer:
                  whitespace:
                    type: custom
                    tokenizer: whitespace
                    filter:
                      - lowercase
                  version:
                    type: custom
                    tokenizer: version
                    char_filter:
                      - version
                    filter:
                      - lowercase
                  camelcase:
                    type: custom
                    tokenizer: camelcase
                    filter:
                      - lowercase
                    alias:
                      - default_index
                      - default_search
                  camelcase_english:
                    type: custom
                    tokenizer: camelcase
                    filter:
                      - english_possessive_stemmer
                      - lowercase
                      - light_english_stemmer
                      - english_stop
#                  default_index:
#                      type: whitespace
#                  default_search:
#                      type: whitespace
        types:
          package:
            indexable_callback: isIndexed
            mappings:
              id:
                type: integer
                store: true
              platform.id:
                type: integer
                store: true
              version:
                type: string
                store: true
                analyzer: version
                norms:
                  enabled: false
              name:
                type: string
                store: true
                analyzer: camelcase
                norms:
                  enabled: false
              description:
                type: string
                store: true
                analyzer: camelcase_english
                norms:
                  enabled: true
              license:
                type: string
                store: true
                analyzer: standard
                norms:
                  enabled: false
              languages:
                type: string
                store: true
                analyzer: simple
                norms:
                  enabled: false
              dependencies:
                type: object
                store: true
                properties:
                  id:
                    type: integer
                    store: true
                  name: 
                    type: string
                    store: true
                    analyzer: camelcase
                    norms:
                      enabled: false
              namespaces:
                type: multi_field
                norms:
                  enabled: false
                fields:
                  namespaces:
                    type: string
                    store: false
                    analyzer: camelcase
                    norms:
                      enabled: true
                  namespacesAnalyzed:
                    type: string
                    store: false
                    analyzer: camelcase_english
                    norms:
                      enabled: true
              classes:
                type: multi_field
                norms:
                  enabled: false
                fields:
                  classes:
                    type: string
                    store: false
                    analyzer: camelcase
                    norms:
                      enabled: true
                  classesAnalyzed:
                    type: string
                    store: false
                    analyzer: camelcase_english
                    norms:
                      enabled: true
            persistence:
              driver: orm
              model: Tugel\TugelBundle\Entity\Package
              provider: ~
              listener: ~
              finder: ~