fos_rest:
    #param_fetcher_listener: true
    #body_listener: true
    #body_converter:
    #    enabled: true
    format_listener: true
#    service:
#        view_handler: tokitime.fos_rest.view_handler
    routing_loader:
        default_format: json
    view:
        serialize_null: true
        view_response_listener: true
        formats:
            json : true
            xml: true
        templating_formats:
            html: true
        force_redirects:
            html: true
            
sensio_framework_extra:
    view:    { annotations: false }