fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        search:
            index_name: ppint
            settings:
                index:
                    analysis:
                        analyzer:
#                            default_index:
#                                type: whitespace
#                            default_search:
#                                type: whitespace
                            whitespace:
                                type: whitespace
                            identifier:
                                type: pattern
                                pattern: "[\\:\\.\\W\\\\]+"
                                lowercase: false
                            camelcase:
                                type: pattern
                                pattern: "([^\\p{L}\\d]+)|(?<=\\D)(?=\\d)|(?<=\\d)(?=\\D)|(?<=[\\p{L}&&[^\\p{Lu}]])(?=\\p{Lu})|(?<=\\p{Lu})(?=\\p{Lu}[\\p{L}&&[^\\p{Lu}]])"
                                lowercase: true
            types:
#                package:
#                    mappings:
#                        name: ~
#                        description: ~
#                        url: ~
#                    persistence:
#                        driver: orm
#                        model: Zeutzheim\PpintBundle\Entity\Package
#                        provider: ~
#                        listener: ~
                version:
                    indexable_callback: isIndexed
                    mappings:
                        name: ~
                        package:
                            type: "object"
                            properties:
                                id: ~ #{ boost: 5 }
                                name: ~ #{ boost: 5 }
                                description: ~ #{ boost: 5 }
                        languages: { analyzer: whitespace }
                        namespaces: { analyzer: identifier }
                        classes: { boost: 1, analyzer: identifier }
                        codeTags: { analyzer: whitespace }
                    persistence:
                        driver: orm
                        model: Zeutzheim\PpintBundle\Entity\Version
                        provider: ~
                        listener: ~
                        finder: ~